apiVersion: networking.k8s.io/v1beta1
kind: IngressClass
metadata:
  name: {{ .Values.controller.ingressClassName }}
  namespace: {{ .Release.Namespace }}
spec:
  controller: traefik.io/ingress-controller
