apiVersion: v1
kind: Service
metadata:
  name: controller
  namespace: {{ .Release.Namespace }}
  {{- if .Values.controller.service.annotations }}
  annotations: {{ toYaml .Values.controller.service.annotations | nindent 4 }}
  {{- end }}
spec:
  type: LoadBalancer
  selector:
    app: traefik-lb
  ports:
    - name: http
      port: 80
      targetPort: tohttps
    - name: https
      port: 443
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: traefik-lb
  ports:
    - name: api
      port: 8080
      targetPort: api
