# Inspired by
# https://github.com/traefik/traefik-helm-chart/tree/master/traefik
rbac:
  enabled: true

controller:
  priorityClassName:
  ingressClassName: traefik
  image:
    repository: traefik
    tag: "v2.6"
    pullPolicy: Always
  service:
    annotations: {}
  resources: {}
